
--- here comes the error!

-- almost!




-- !!!


-- !!

analyzer function error_(msg)
    error(msg:GetData())
end

-- ERROR4
error_("finally the error!")